name: Release

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: "https://registry.npmjs.org"

      - name: Fetch git tags
        run: git fetch --tags --force
        
      - name: Cache esy dependencies
        uses: actions/cache@v1
        id: cache
        with:
          path: _export
          key: ${{ runner.OS }}-build-${{ hashFiles('esy.lock/index.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
            
      - name: Install esy
        run: npm i -g esy@0.6.7

      - name: Import dependencies
        if: steps.cache.outputs.cache-hit == 'true'
        run: esy import-build _export/*

      - name: Install deps
        run: esy install
    
      - name: Build app
        run: esy build

      - name: Export dependencies
        run: esy export-dependencies
    
      - name: Upload artifacts for ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}
          path: _build/default/src/findr.exe

  publish:
   needs: build
   name: Publish
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Make _release folder
        run: node scripts/make-release.js
      
      - name: Download linux artifacts
        uses: actions/download-artifact@master
        with:
          name: ubuntu-latest
          path: _release/platform-linux-x64

      - name: Download mac artifacts
        uses: actions/download-artifact@master
        with:
          name: macos-latest
          path: _release/platform-darwin-x64

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Create archives for Github release
        run: |
          cd _release/platform-darwin-x64
          zip -r ../../spin-darwin-x64.zip .
          cd ../..
          cd _release/platform-linux-x64
          zip -r ../../spin-linux-x64.zip .
          cd ../..

      - name: Create Github release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}
          release_name: Release ${{ steps.get-latest-tag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload spin-darwin-x64.zip to Github release 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: spin-darwin-x64.zip
          asset_name: spin-darwin-x64.zip
          asset_content_type: application/gzip
      
      - name: Upload spin-linux-x64.zip to Github release 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: spin-linux-x64.zip
          asset_name: spin-linux-x64.zip
          asset_content_type: application/gzip

      - name: Release npm package
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm config set scope "@vmarcosp"
          npm publish --access public
        working-directory: ./_release
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
