name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Install esy
        run: npm i -g esy@latest

      - name: Install and build
        run: esy && esy npm-release
    
      - name: Update release package
        run: node scripts/transform-release.js
